As our discussions veer towards meme and the culture surrounding them, I think it’s important to note that memes are capable of a lot more than people sometimes think. It’s accurate to state that memes represent a culture while also contributing to it, referencing already existing media, but also creating their own strange culture. Memes are part of regular culture now, especially for certain age groups, but certainly for everyone who spends any time on the internet at all. Memes bring people together, give people something widespread to relate to, make people feel less alone and more a part of something. Memes can also alienate those who don’t understand them, unite people who otherwise feel ostracized from society and… serve as propaganda to turn vulnerable groups of people into extremists.

![Pepe the Frog](https://i.kym-cdn.com/entries/icons/original/000/017/618/pepefroggie.jpg)
[https://knowyourmeme.com/memes/pepe-the-frog](https://knowyourmeme.com/memes/pepe-the-frog)

So. This guy. 

After we discussed memes and their role within culture, my first thoughts were about [Pepe the Frog](https://knowyourmeme.com/memes/pepe-the-frog). Originally created by Matt Furie as a character in a comic series, Pepe has evolved to become so much more. Interestingly enough, he has come to represent the alt-right movement. [This article](https://www.thedailybeast.com/how-pepe-the-frog-became-a-nazi-trump-supporter-and-alt-right-symbol) from the Daily Beast discusses Pepe’s transformation into a neo-nazi icon over time. As referenced in the article, white nationalists have claimed that there is, “an actual campaign to reclaim Pepe from normies.” Pepe has not become this alt-right icon by accident; his weaponization has been by design. The same white nationalist as above stated, “In a sense, we’ve managed to push white nationalism into a very mainstream position.” Pepe wasn’t designed to push alt-right ideals, and his creator has actually denounced his own character because the associations run so deep. But Pepe has become this icon nonetheless, and brought to the forefront of meme culture. 

When Rabinowitz shared the claim that “memes make us do things” in [The Meme as Meme](http://nautil.us/issue/5/fame/the-meme-as-meme), I initially didn’t know what exactly she meant. What do memes make us do? Do they force us to engage with others who enjoy and employ the same memes? Do they alienate us should we fail to understand them, which inspires us to educate ourselves about the culture that they reference? Then, I realized: after enough exposure, and with fitting enough environmental factors, memes can inspire the extreme ideologies that do make people do things. Even if memes are simply a vehicle in achieving that goal, their ability to go viral and impact large amounts of people lends itself pretty well to propaganda. Is this something that is important to combat specifically, or is it something that would happen regardless of the medium? And, if we do want to do something about it, how would we go about reclaiming memes, or limiting their circulation, to avoid this?
